# This is a basic workflow to help you get started with Actions

name: CI Django & Postgres Tests

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy django app for begginers
    # define a runner (machine you want to run this pipeline)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test
      
      - name: Build Docker Image
        uses: docker/setup-buildx-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tag : ${{ secrets.DOCKER_USERNAME}}/CICD:latest
      - name : Login to Docker Hub
        uses : docker/login-action@v1
        with :
          username : ${{ secrets.DOCKER_USERNAME}}
          password : ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name : Push to DOcker Hub
        uses: docker/setup-buildx-action@v2
        with :
          context : .
          dockerfile : Dockerfile 
          push : true
          tag : ${{ secrets.DOCKER_USERNAME}}/CICD:latest


